# Site settings
title: "Felix.Hu 简历"
description: "Felix.Hu 个人简历"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Felix.Hu"
resume_title:                   "iOS 开发者、Web3 游民"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hulj3733@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "四川 • 成都<br>PMP/CET4"
display_header_contact_info:    "true"

resume_header_intro: "<p>  工作以来，主要从事iOS开发、项目管理、项目实训及文档编写相关工作，积累了丰富的开发经验和项目经验。能快速根据项目需求完成业务逻辑构建和代码实现<ul class=\"resume-item-list\"><li>熟练运用Swift/Objective-C开发语言、主流项目框架及常用数据结构、通信协议、算法和设计模式</li><li>熟练运用RxSwift+MVVM及组件化、核心动画构建、多线程操作等技术</li><li>熟练掌握前后端会话机制及数据通信方式，能快速对接三方SDK</li><li>熟悉HTML/CSS/JS/Node.js</li><li>熟悉Solidity、Ganache、OpenZeppelin、Remix进行合约开发部署及Web3生态相关业务</li></ul></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kk-vv"
  # resume_twitter_url:           "insert URL here"
  # resume_dribbble_url:          "insert URL here"
  # resume_facebook_url:          "insert URL here"
  # resume_linkedin_url:          "insert URL here"
  # resume_instagram_url:         "insert URL here"
  # resume_website_url:           "insert URL here"
  # resume_medium_url:            "insert URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
